### ISSUE TITLE
Remote buf plugin doesn't exist

### ISSUE THREAD

**Issue by wizlif** [so1n/protobuf_to_pydantic#47]
**Describe the bug**
Seems the buf registry plugin doesn't exist.

**To Reproduce**
```yaml
  - plugin: buf.build/python-pai/protobuf-to-pydantic:v0.2.1
    opt:
      - plugin_config_py_code_base64=aW1wb3J0IGxvZ2dpbmcKCmxvZ2dpbmcuYmFzaWNDb25maWcoZm9ybWF0PSJbJShhc2N0aW1lKXMgJShsZXZlbG5hbWUpc10gJShtZXNzYWdlKXMiLCBkYXRlZm10PSIleS0lbS0lZCAlSDolTTolUyIsIGxldmVsPWxvZ2dpbmcuSU5GTykKCgpkZWYgZGVmYXVsdF9mdW5jKCkgLT4gaW50OgogICAgcmV0dXJuIDEKCmxvY2FsX2RpY3QgPSB7CiAgICAiZGVmYXVsdF9mdW5jIjogZGVmYXVsdF9mdW5jLAp9Cg
      - plugin_config_module_name=plugin_config
 ```

`Failure: plugin "buf.build/python-pai/protobuf-to-pydantic" was not found`
